{"variants":[{"paths":["\/documentation\/n2framework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/n2framework"]}],"kind":"symbol","hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collection","symbolKind":"module","modules":[{"name":"N2Framework"}],"roleHeading":"Framework","title":"N2Framework","externalID":"N2Framework"},"topicSections":[{"identifiers":["doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2Manager"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2ManagerDelegate"]},{"identifiers":["doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/PresentationTypeN2","doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/TypeOfEnvironmentN2"],"title":"Enumerations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework"},"references":{"doc://com.bt.N2Framework/documentation/N2Framework/PresentationTypeN2":{"type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationTypeN2","kind":"identifier"}],"role":"symbol","url":"\/documentation\/n2framework\/presentationtypen2","navigatorTitle":[{"kind":"identifier","text":"PresentationTypeN2"}],"title":"PresentationTypeN2","kind":"symbol","identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/PresentationTypeN2"},"doc://com.bt.N2Framework/documentation/N2Framework/N2ManagerDelegate":{"title":"N2ManagerDelegate","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"N2ManagerDelegate"}],"identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2ManagerDelegate","kind":"symbol","url":"\/documentation\/n2framework\/n2managerdelegate","navigatorTitle":[{"text":"N2ManagerDelegate","kind":"identifier"}]},"doc://com.bt.N2Framework/documentation/N2Framework/TypeOfEnvironmentN2":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"TypeOfEnvironmentN2","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/TypeOfEnvironmentN2","url":"\/documentation\/n2framework\/typeofenvironmentn2","title":"TypeOfEnvironmentN2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TypeOfEnvironmentN2","kind":"identifier"}]},"doc://com.bt.N2Framework/documentation/N2Framework/N2Manager":{"title":"N2Manager","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"N2Manager"}],"identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2Manager","kind":"symbol","url":"\/documentation\/n2framework\/n2manager","navigatorTitle":[{"text":"N2Manager","kind":"identifier"}]},"doc://com.bt.N2Framework/documentation/N2Framework":{"role":"collection","kind":"symbol","abstract":[],"title":"N2Framework","url":"\/documentation\/n2framework","identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework","type":"topic"},"doc://com.bt.N2Framework/documentation/N2Framework/N2FrameworkVersionNumber":{"identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2FrameworkVersionNumber","type":"topic","url":"\/documentation\/n2framework\/n2frameworkversionnumber","abstract":[{"type":"text","text":"Project version number for N2Framework."}],"fragments":[{"text":"N2FrameworkVersionNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"N2FrameworkVersionNumber"},"doc://com.bt.N2Framework/documentation/N2Framework/N2FrameworkVersionString":{"identifier":"doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2FrameworkVersionString","kind":"symbol","fragments":[{"kind":"identifier","text":"N2FrameworkVersionString"}],"title":"N2FrameworkVersionString","type":"topic","url":"\/documentation\/n2framework\/n2frameworkversionstring","abstract":[{"type":"text","text":"Project version string for N2Framework."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2FrameworkVersionNumber","doc:\/\/com.bt.N2Framework\/documentation\/N2Framework\/N2FrameworkVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"}]}]}